export const apiEnpoints = {
	API_VERSION: '/api/v1/admin',
	API_VERSION_V1: '/api/v1',
	COACHING_CENTERS: '/coaching_centers',
	DASHBOARD: '/dashboard',
	USERS: '/users',
	BATCHES: '/batches',
	LOCATION: '/locations',
	COURSES: '/courses',
	SUBJECTS: '/subjects',
	ROLES: '/users/list_roles',
	INSTRUCTOR: '/users/instructors',
	ASSIGN: '/users/assign',
	BATCH_STUDENTS: '/batch/batch_users',
	QUALIFICATION: '/users/user_qualifications',
	QUESTIONS: '/questions',
	CHAPTERS: '/chapters',
	TOPICS: '/topics',
	MASTER: '/master',
	QUESTION_TYPES: '/question_types',
	EXAM_TYPES: '/exam_types',
	QUESTION_LEVELS: '/question_levels',
	QUESTION_SOURCES: '/question_sources',
};
